# Generated by Django 3.2.9 on 2022-01-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_shopuserprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
