# Generated by Django 4.0 on 2022-01-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_shopuserprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='langs',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='язык'),
        ),
    ]
